name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/alpine:3.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nushell
        run: |
          apk add --no-cache nushell

      - name: Run unit tests
        run: |
          cd tests
          nu run_all_tests.nu

  build:
    name: Build Container Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: false
          tags: team-friendship-hour:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test container startup
        run: |
          docker build -t team-friendship-hour:test -f Containerfile .
          docker run -d --name test-container -p 8080:8080 team-friendship-hour:test
          sleep 5
          curl -f http://localhost:8080/ || exit 1
          docker stop test-container
          docker rm test-container

  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    container:
      image: docker.io/library/alpine:3.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nushell
        run: |
          apk add --no-cache nushell

      - name: Check Nushell syntax
        run: |
          find src -name "*.nu" -exec nu -c "open {} | null" \;
          find tests -name "*.nu" -exec nu -c "open {} | null" \;
